platform :ios, '6.0'
pod 'DTCoreText', '~>1.6.10'
pod 'AFNetworking', '~>2.1.0'
pod 'hpple', '~> 0.2.0'
pod 'FlurrySDK', '~> 4.3.2'
pod 'Appirater', '~> 2.0.2'
pod 'SDWebImage', '~> 3.5.2'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVWebViewController', '~> 1.0'
pod 'RegexKitLite', '~> 4.0'
pod 'NSDate+TimeAgo', '~> 1.0.2'
pod 'FXBlurView', '~> 1.5.3'
pod 'Google-AdMob-Ads-SDK', '~> 6.8.0'