platform :ios, '6.0'
pod 'DTCoreText', '~>1.6.10'
pod 'AFNetworking', '~>2.1.0'
pod 'hpple', '~> 0.2.0'
pod 'QuickDialog', '~>0.9.1'
pod 'GoogleAnalytics-iOS-SDK', '~>3.0.3'
pod 'FlurrySDK', '~> 4.3.0'
pod 'Appirater', '~> 2.0.2'
pod 'SDWebImage', '~> 3.5.2'
pod 'SVProgressHUD', '~> 1.0'
pod 'RegexKitLite', '~> 4.0'